### ISSUE TITLE
any plan for MRP function?

### ISSUE THREAD

**Issue by frankgp** [rtlabs-com/p-net#197] opened 2020-10-19 04:10 UTC
For Profinet-IO. the MRP is normally function and it is basic requirements.

**Comment by pyhys** [comment] 2020-10-19 06:07
Hi, thanks for your input!
We need to finish conformance class B before this.

**Comment by jeppefrandsen** [comment] 2022-06-14 16:04
+1

**Comment by pyhys** [comment] 2024-04-17 12:16
Closing as this is a duplicate of #575

**Closed by pyhys** 2024-04-17 12:16 UTC
Labels: enhancement

**Comment by lin-jingjie** [comment] 2025-09-04 07:01
When will MRP be realized?  thanks！
